name: quartet_dart
description: Quartet is a huge collection of useful string manipulation functions written in the Dart language.
# version: 1.0.0
# homepage: https://xiaoru.li
# author: Xiaoru Li <hello@xiaoru.li>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
